### ISSUE TITLE
[Solved] Installation issues. Shader validation source file does not exist 

### ISSUE THREAD

**Issue by BrundleThwaite** [Unity-China/com.unity.hairfx#4]
This is the error I get upon installation. 

>"Shader Graph at Packages/cn.unity.hairfx.hdrp/Editor/ShaderGraph/HDPipeline/SG_Hair.shadergraph has 1 error(s), the first is: >Validation: Source file does not exist. A valid .hlsl, .cginc, or .cg file must be referenced
>UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)"

I do not seem to have the GetExpandedVertex shader.

![HairFX](https://user-images.githubusercontent.com/18170954/208877324-a7c2fd4f-ea10-411f-becb-8d0d56294698.jpg)

I am using Unity 2022.2.0f1
HDRP 14.0.4

This is using a brand new empty project.

The manifest additions were:

>    "cn.unity.hairfx.core": "https://github.com/Unity-China/cn.unity.hairfx.core.git",  
>    "cn.unity.hairfx.hdrp": "https://github.com/Unity-China/cn.unity.hairfx.hdrp.git"

**Comment by michael430** [comment]
Updated Shaders and solved the errors
