### ISSUE TITLE
Maya plugin does not work with 2023.2

### ISSUE THREAD

**Issue by adamzeliasz1** [Unity-China/com.unity.hairfx#5]
After following the installation instructions I'm getting this error:
// Error: file: C:/Program Files/Autodesk/Maya2023/scripts/others/pluginWin.mel line 316:  (TressFX_Exporter)

The Plugin-Manager sees it, but it will not let me select the "Loaded" option without giving me the error above.

What version(s) of Maya work with this plugin? Thanks.

**Comment by michael430** [comment]
Yes, It mentioned [here](https://github.com/Unity-China/cn.unity.hairfx.core/blob/main/Maya_TressFX_Exporter~/Install%20Readme.txt) already, because the plugin is original from AMD TressFX, we will try to upgrade it in future

**Comment by michael430** [comment]
Updated new plugins to support new version of Maya 2022 to 2024

> After following the installation instructions I'm getting this error: // Error: file: C:/Program Files/Autodesk/Maya2023/scripts/others/pluginWin.mel line 316: (TressFX_Exporter)
> 
> The Plugin-Manager sees it, but it will not let me select the "Loaded" option without giving me the error above.
> 
> What version(s) of Maya work with this plugin? Thanks.
